export const coursesData = [
  {
    id: 1,
    name: "React JS",
    description: "React Js course from zero to hero",
    author: "John Bura",
    ratings: 4.3,
    price: 100,
    image: "https://ashokitech.com/uploads/course/react-js-online-training.png",
  },
  {
    id: 2,
    name: "Node.js for Beginners",
    description:
      "Learn Node.js basics and build your first server-side application.",
    author: "Emma Johnson",
    ratings: 4.5,
    price: 120,
    image:
      "https://www.itrainu.in/wp-content/uploads/2023/08/node-js-jpeg.webp",
  },
  {
    id: 3,
    name: "Python Programming Masterclass",
    description:
      "Comprehensive Python programming course for beginners and advanced learners.",
    author: "Alex Smith",
    ratings: 4.7,
    price: 150,
    image: "https://trisectinstitute.com/wp-content/uploads/2021/12/best-python-training.png",
  },
  {
    id: 4,
    name: "JavaScript Fundamentals",
    description: "Essential JavaScript concepts for web development.",
    author: "Maria Rodriguez",
    ratings: 4.2,
    price: 80,
    image: "https://www.classcentral.com/report/wp-content/uploads/2017/10/js-and-frameworks-banner.png",
  },
  {
    id: 5,
    name: "Angular Complete Guide",
    description: "Master Angular and build powerful web applications.",
    author: "David Williams",
    ratings: 4.6,
    price: 130,
    image: "https://trisectinstitute.com/wp-content/uploads/2021/12/best-angular-training.png",
  },
  {
    id: 6,
    name: "Java Programming Essentials",
    description: "Learn core Java programming concepts and principles.",
    author: "Emily Chen",
    ratings: 4.4,
    price: 110,
    image: "https://www.classcentral.com/report/wp-content/uploads/2022/05/Java-BCG-Banner.png",
  },
  {
    id: 7,
    name: "Django Web Development",
    description: "Build dynamic web applications with Django framework.",
    author: "Michael Adams",
    ratings: 4.8,
    price: 160,
    image: "https://1.bp.blogspot.com/-42WDaVJa3j8/Xw73Ww75gCI/AAAAAAAAhHg/ePGNcnUyddEOg8NSXoAEe0Upiu3rUwkdACLcBGAsYHQ/w1200-h630-p-k-no-nu/Django%2B3%2B-%2BFull%2BStack%2BWebsites%2Bwith%2BPython%2BWeb%2BDevelopment%2B-%2Bbest%2BUdemy%2Bcourse.png",
  },
  {
    id: 8,
    name: "Full Stack Development Bootcamp",
    description:
      "Comprehensive bootcamp covering front-end and back-end development.",
    author: "Sophia Lewis",
    ratings: 4.9,
    price: 200,
    image: "https://www.upshottechnologies.in/images/course/full-stack-training-in-bangalore.jpg"},
  {
    id: 9,
    name: "Vue.js Essentials",
    description: "Learn Vue.js and build modern user interfaces.",
    author: "Daniel Turner",
    ratings: 4.5,
    price: 120,
    image: "https://asset-cdn.learnyst.com/assets/schools/2410/courses/92665/vue_course_lu39t.png",
  },
  {
    id: 10,
    name: "Data Science with Python",
    description: "Explore data science concepts using Python programming.",
    author: "Sophie Miller",
    ratings: 4.6,
    price: 140,
    image: "https://cdn.analyticsvidhya.com/wp-content/uploads/2023/01/1.png",
  },
  {
    id: 11,
    name: "C# Fundamentals",
    description: "Introduction to C# programming language.",
    author: "Andrew Turner",
    ratings: 4.2,
    price: 90,
    image: "https://miro.medium.com/v2/resize:fit:960/0*hep8e7e_VoqbPNgB.jpg",
  },
];
